export const BOTTOM_NAV_MIN_HEIGHT = 62;
export const ANDROID_SYSTEM_BOTTOM_CLEARANCE = 24;
export const APP_OWNED_BOTTOM_CHROME_ANDROID_CLEARANCE = 56;
export const APP_CONTENT_BOTTOM_CLEARANCE = BOTTOM_NAV_MIN_HEIGHT + ANDROID_SYSTEM_BOTTOM_CLEARANCE + 24;
